version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SELENIUM_DRIVER_URL: http://webdriver_chrome:4444/wd/hub
      TZ: Asia/Tokyo
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - webdriver_chrome
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  webdriver_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
volumes:
  db-volume:
